/**
 * MPLP Protocol v1.0.0 — Frozen Specification
 * Freeze Date: 2025-12-03
 * Status: FROZEN (no breaking changes permitted)
 * Governance: MPLP Protocol Governance Committee (MPGC)
 *
 * © 2025 邦士（北京）网络科技有限公司. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * http://www.apache.org/licenses/LICENSE-2.0
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Core Module Core Protocol: Describes the minimal required semantics (Core Profile) for an MPLP protocol instance's version, enabled modules, and overall state.
 */
export interface Core {
  /** [PROTOCOL-CORE] MPLP protocol and schema metadata. */
  meta: any;
  /** [PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status. */
  governance?: object;
  /** [PROTOCOL-CORE] Global unique identifier for the current Core instance. */
  core_id: any;
  /** [PROTOCOL-CORE] Major version number of the current MPLP protocol instance (e.g., 1.0.0). */
  protocol_version: string;
  /** [PROTOCOL-CORE] Lifecycle status of the current Core instance. */
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  /** [PROTOCOL-CORE] List of L2 modules enabled in the current protocol instance. */
  modules: any[];
  /** [PROTOCOL-CORE] Main Trace reference bound to this Core instance, used for auditing Core layer configuration changes. */
  trace?: any;
  /** [PROTOCOL-CORE] List of key events related to this Core instance (version upgrades, module enable/disable, etc.). */
  events?: any[];
}
