/**
 * MPLP Protocol v1.0.0 — Frozen Specification
 * Freeze Date: 2025-12-03
 * Status: FROZEN (no breaking changes permitted)
 * Governance: MPLP Protocol Governance Committee (MPGC)
 *
 * © 2025 邦士（北京）网络科技有限公司. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * http://www.apache.org/licenses/LICENSE-2.0
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Dialog Module Core Protocol: Describes the dialog interaction semantics in multi-agent systems, adopting Minimal Protocol Format aligned with OpenAI/Anthropic standards.
 */
export interface Dialog {
  /** [PROTOCOL-CORE] MPLP protocol and schema metadata. */
  meta: any;
  /** [PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status. */
  governance?: object;
  /** [PROTOCOL-CORE] Global unique identifier for the Dialog. */
  dialog_id: any;
  /** [PROTOCOL-CORE] Associated Context ID. */
  context_id: any;
  /** [PROTOCOL-CORE] Dialog thread ID (for multi-turn dialog grouping). */
  thread_id?: any;
  /** [PROTOCOL-CORE] Dialog status. */
  status: 'active' | 'paused' | 'completed' | 'cancelled';
  /** [PROTOCOL-CORE] Dialog message list (Minimal Protocol Format). */
  messages: any[];
  /** [PROTOCOL-CORE] Dialog start time (ISO 8601). */
  started_at?: string;
  /** [PROTOCOL-CORE] Dialog end time (ISO 8601). */
  ended_at?: string;
  /** [PROTOCOL-CORE] Audit trace reference associated with this dialog. */
  trace?: any;
  /** [PROTOCOL-CORE] List of key events directly related to this dialog. */
  events?: any[];
}
