name: ✨ Feature Request
description: Suggest a new feature for MPLP v1.0 Alpha
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for MPLP v1.0 Alpha!
        
        Your feedback helps shape the future of the Multi-Agent Protocol Lifecycle Platform.

  - type: checkboxes
    id: alpha-acknowledgment
    attributes:
      label: Alpha Version Acknowledgment
      description: Please confirm you understand this is an Alpha release
      options:
        - label: I understand this is MPLP v1.0 Alpha and the roadmap may change
          required: true
        - label: I have checked the [Roadmap](../ROADMAP.md) to see if this feature is already planned
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New API endpoint
        - New module functionality
        - Performance improvement
        - Developer experience enhancement
        - Documentation improvement
        - Integration with external service
        - Protocol enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: affected-module
    attributes:
      label: Affected Module
      description: Which MPLP module would this feature affect?
      options:
        - Core (MPLPCore)
        - Context
        - Plan
        - Role
        - Confirm
        - Trace
        - Extension
        - Dialog
        - Collab
        - Network
        - CoreOrchestrator
        - Multiple modules
        - New module
        - Cross-cutting concern

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing...
        
        For example:
        - "Currently, there's no way to..."
        - "It's difficult to..."
        - "Users need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        Describe how you think this feature should work...
        
        For example:
        - "Add a new API method that..."
        - "Extend the existing functionality to..."
        - "Create a new module that..."
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this involves API changes, describe the proposed API
      render: typescript
      placeholder: |
        // Example API design
        interface NewFeature {
          method(): Promise<Result>;
        }
        
        // Usage example
        const result = await mplp.newModule.newMethod({
          parameter: 'value'
        });

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a developer, I want to... so that...
        2. When building multi-agent systems, I need to... because...
        3. In production environments, this would help...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered...
        
        For example:
        - "I tried using... but it doesn't work because..."
        - "A workaround is... but it's not ideal because..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my adoption of MPLP
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple addition or modification
        - Medium - Moderate changes required
        - High - Significant architectural changes
        - Unknown - Not sure about implementation complexity

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      placeholder: |
        Describe any potential breaking changes this feature might require...
        
        For Alpha releases, breaking changes are acceptable but should be documented.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: |
        Add any other context, mockups, examples, or related issues...
        
        You can also include:
        - Links to similar features in other projects
        - Screenshots or diagrams
        - Performance considerations
        - Security implications

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false
        - label: I am willing to help with documentation
          required: false
        - label: I am willing to provide feedback during development
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I understand this is an Alpha release and priorities may change
          required: true
