name: 功能请求 / Feature Request
description: 建议新功能或改进现有功能 / Suggest a new feature or improvement to existing functionality
title: "[功能请求/Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 MPLP 项目提出功能建议！
        
        Thank you for suggesting a feature for the MPLP project!
        
        请详细描述您希望添加或改进的功能，这将帮助我们更好地理解您的需求。
        Please describe in detail the feature you would like to add or improve, which will help us better understand your needs.

  - type: dropdown
    id: feature-category
    attributes:
      label: 功能类别 / Feature Category
      description: 这个功能请求属于哪个类别 / Which category does this feature request belong to
      options:
        - 核心协议 / Core Protocol
        - JSON Schema 扩展 / JSON Schema Extension
        - 文档生成 / Documentation Generation
        - 工具链改进 / Toolchain Improvement
        - 开发体验 / Developer Experience
        - 性能优化 / Performance Optimization
        - 集成支持 / Integration Support
        - 监控和分析 / Monitoring and Analytics
        - 用户界面 / User Interface
        - API 扩展 / API Extension
        - 其他 / Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级 / Priority
      description: 您认为这个功能的重要性如何 / How important do you think this feature is
      options:
        - 低 / Low - 有了更好，没有也可以 / Nice to have, but not essential
        - 中 / Medium - 会显著改善使用体验 / Would significantly improve user experience
        - 高 / High - 对工作流程很重要 / Important for workflow
        - 紧急 / Critical - 阻碍当前使用 / Blocking current usage
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 问题描述 / Problem Statement
      description: 您遇到了什么问题，或者想要改进什么 / What problem are you encountering, or what would you like to improve
      placeholder: |
        请描述：/ Please describe:
        - 当前的痛点或限制 / Current pain points or limitations
        - 为什么现有的解决方案不够好 / Why existing solutions are not sufficient
        - 这个问题如何影响您的工作流程 / How this problem affects your workflow
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 建议的解决方案 / Proposed Solution
      description: 您希望如何解决这个问题 / How would you like to solve this problem
      placeholder: |
        请详细描述您建议的解决方案：/ Please describe your proposed solution in detail:
        
        - 功能应该如何工作 / How the feature should work
        - 用户界面或 API 设计 / User interface or API design
        - 与现有功能的集成方式 / How it integrates with existing features
        - 预期的用户体验 / Expected user experience
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景 / Use Cases
      description: 这个功能将在哪些场景下使用 / In what scenarios will this feature be used
      placeholder: |
        请提供具体的使用场景：/ Please provide specific use cases:
        
        1. 场景一 / Scenario 1: ...
        2. 场景二 / Scenario 2: ...
        3. 场景三 / Scenario 3: ...
        
        对于每个场景，请描述：/ For each scenario, please describe:
        - 用户角色 / User role
        - 具体操作步骤 / Specific operation steps
        - 期望的结果 / Expected outcome
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives Considered
      description: 您是否考虑过其他解决方案 / Have you considered other solutions
      placeholder: |
        请描述您考虑过的其他方案：/ Please describe other alternatives you have considered:
        
        - 方案 A / Alternative A: ...
        - 方案 B / Alternative B: ...
        - 为什么这些方案不够理想 / Why these alternatives are not ideal
        - 现有的变通方法 / Current workarounds

  - type: textarea
    id: technical-considerations
    attributes:
      label: 技术考虑 / Technical Considerations
      description: 实现这个功能需要考虑哪些技术方面 / What technical aspects need to be considered for implementing this feature
      placeholder: |
        请考虑以下技术方面：/ Please consider the following technical aspects:
        
        - 向后兼容性 / Backward compatibility
        - 性能影响 / Performance impact
        - 安全考虑 / Security considerations
        - 依赖关系 / Dependencies
        - 测试策略 / Testing strategy
        - 文档需求 / Documentation requirements

  - type: textarea
    id: mockups-examples
    attributes:
      label: 示例和模拟 / Examples and Mockups
      description: 提供代码示例、界面模拟或其他视觉材料 / Provide code examples, interface mockups, or other visual materials
      placeholder: |
        请提供：/ Please provide:
        
        - 代码示例 / Code examples
        - 配置文件示例 / Configuration file examples
        - API 调用示例 / API call examples
        - 界面截图或模拟图 / Interface screenshots or mockups
        - 流程图 / Flow diagrams
      render: markdown

  - type: dropdown
    id: implementation-complexity
    attributes:
      label: 实现复杂度估计 / Implementation Complexity Estimate
      description: 您认为实现这个功能的复杂度如何 / How complex do you think implementing this feature would be
      options:
        - 简单 / Simple - 几小时到一天 / A few hours to a day
        - 中等 / Medium - 几天到一周 / A few days to a week
        - 复杂 / Complex - 几周到一个月 / A few weeks to a month
        - 非常复杂 / Very Complex - 超过一个月 / More than a month
        - 不确定 / Not Sure
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿 / Contribution Willingness
      description: 您是否愿意参与实现这个功能 / Are you willing to participate in implementing this feature
      options:
        - label: 我愿意参与设计讨论 / I am willing to participate in design discussions
          required: false
        - label: 我愿意提供测试和反馈 / I am willing to provide testing and feedback
          required: false
        - label: 我愿意编写代码实现 / I am willing to write code implementation
          required: false
        - label: 我愿意编写文档 / I am willing to write documentation
          required: false
        - label: 我愿意帮助推广这个功能 / I am willing to help promote this feature
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 附加信息 / Additional Context
      description: 任何其他相关信息 / Any other relevant information
      placeholder: |
        - 相关的外部资源或参考 / Related external resources or references
        - 类似功能在其他项目中的实现 / Similar features implemented in other projects
        - 社区讨论或反馈 / Community discussions or feedback
        - 时间敏感性 / Time sensitivity

  - type: checkboxes
    id: terms
    attributes:
      label: 确认 / Confirmation
      description: 请确认以下事项 / Please confirm the following
      options:
        - label: 我已经搜索了现有的 Issues 和功能请求，确认这不是重复的 / I have searched existing issues and feature requests and confirmed this is not a duplicate
          required: true
        - label: 我理解这个功能请求将被公开讨论 / I understand this feature request will be discussed publicly
          required: true
        - label: 我理解功能的实现可能需要时间，并且可能会根据项目优先级进行调整 / I understand that feature implementation may take time and may be adjusted based on project priorities
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **感谢您的功能建议！/ Thank you for your feature suggestion!**
        
        我们会仔细评估您的建议，并在适当的时候与您讨论实现细节。
        
        We will carefully evaluate your suggestion and discuss implementation details with you when appropriate.
        
        **下一步 / Next Steps:**
        1. 项目维护者会审查您的请求 / Project maintainers will review your request
        2. 可能会有进一步的讨论和澄清 / There may be further discussion and clarification
        3. 如果被接受，会被添加到项目路线图 / If accepted, it will be added to the project roadmap
        4. 实现完成后会通知您 / You will be notified when implementation is complete