/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Common type definitions used across MPLP modules to ensure consistency and reduce duplication.
 */
export interface MplpCommonTypes {
}

export type MplpId = any;

export type Ref = object;

export type BaseMeta = any;
