/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Base model for all event structures in MPLP. Designed based on CloudEvents v1.0 core fields, providing unified event identification, type, source, and timestamp. ExecutionEvent, StateTransitionEvent, etc., are extensions of this.
 */
export interface MplpEvents {
  /** Unique identifier for the event (UUID v4). */
  event_id: any;
  /** Event type identifier, e.g., execution.started / vsl.transition.applied / plan.created. Uses dot-separated namespace format. */
  event_type: string;
  /** Event source, typically a module or component identifier. Can be a module name (e.g., 'context') or component path (e.g., 'runtime.ael'). */
  source: string;
  /** Event occurrence time (ISO 8601 format). */
  timestamp: string;
  /** Optional trace ID to associate the event with a specific Trace. */
  trace_id?: any;
  data?: any;
}
