/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Unified identifier type used for contextId/planId/traceId/eventId, etc. Uses UUID v4 standard to ensure global uniqueness and collision-free generation in distributed environments.
 */
export interface MplpIdentifiers {
}
