/**
 * Copyright 2025 邦士（北京）网络科技有限公司.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Structured learning sample for MPLP v1.0 runtimes.
 */
export interface MplpLearningSample {
  /** Unique identifier for this learning sample. */
  sample_id: any;
  /** Project identifier this sample belongs to. */
  project_id: string;
  /** Structured representation of the original intent (can reference Context/Plan). */
  intent_before?: { [key: string]: any };
  /** Structured representation of the plan used (can reference Plan module). */
  plan?: { [key: string]: any };
  /** Array of delta intents proposed/applied. */
  delta_intents?: { [key: string]: any }[];
  /** Optional snapshot or summary of the knowledge graph before the change. */
  graph_before?: { [key: string]: any };
  /** Optional snapshot or summary of the knowledge graph after the change. */
  graph_after?: { [key: string]: any };
  /** Sequence of pipeline stages traversed. */
  pipeline_path?: string[];
  /** Whether the action/intent succeeded. */
  success_flag: boolean;
  /** Error details if action failed. */
  error_info?: object;
  /** LLM token consumption metrics. */
  token_usage?: object;
  /** Execution time in milliseconds. */
  execution_time_ms?: number;
  /** Impact score (0.0-1.0). */
  impact_score?: number;
  /** Human feedback on the action/result. */
  user_feedback?: object;
  /** Governance rules evaluated during execution. */
  governance_decisions?: { [key: string]: any }[];
  /** Execution timeline. */
  timestamps: object;
  /** Additional metadata (extensibility point). */
  metadata?: { [key: string]: any };
  /** Optional vendor-specific extensions. Structure is implementation-defined and MUST NOT conflict with core protocol fields. */
  vendor_extensions?: { [key: string]: any };
}
