/**
 * Copyright 2025 邦士（北京）网络科技有限公司.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Common metadata structure for all MPLP objects. Provides version control, creation info, tags, and cross-cutting concern declarations. All top-level objects in L2/L3/L4 should include the meta field.
 */
export interface MplpMetadata {
  /** MPLP protocol version, using Semantic Versioning. */
  protocol_version: string;
  /** Schema version used by the current object, using Semantic Versioning. */
  schema_version: string;
  /** Object creation time (ISO 8601 format). */
  created_at?: string;
  /** Creator identifier (User ID / Agent Name / System ID). */
  created_by?: string;
  /** Object last update time (ISO 8601 format). */
  updated_at?: string;
  /** Last updater identifier. */
  updated_by?: string;
  /** Set of tags for indexing/search. Supports custom classification and retrieval. */
  tags?: string[];
  /** Declares cross-cutting concerns enabled for the current object (one of the 9 concerns in Governance Plane). */
  cross_cutting?: 'coordination' | 'error-handling' | 'event-bus' | 'orchestration' | 'performance' | 'protocol-version' | 'security' | 'state-sync' | 'transaction'[];
}
