/**
 * Copyright 2025 邦士（北京）网络科技有限公司.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Network Module Core Protocol: Describes the minimal required semantics (Core Profile) for the topology and node collection of a multi-agent collaboration network.
 */
export interface Network {
  /** [PROTOCOL-CORE] MPLP protocol and schema metadata. */
  meta: any;
  /** [PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status. */
  governance?: object;
  /** [PROTOCOL-CORE] Global unique identifier for the network. */
  network_id: any;
  /** [PROTOCOL-CORE] Identifier of the Context this network belongs to. */
  context_id: any;
  /** [PROTOCOL-CORE] Network name. */
  name: string;
  /** [PROTOCOL-CORE] Brief description of the network. */
  description?: string;
  /** [PROTOCOL-CORE] Network topology type. */
  topology_type: 'single_node' | 'hub_spoke' | 'mesh' | 'hierarchical' | 'hybrid' | 'other';
  /** [PROTOCOL-CORE] Network lifecycle status. */
  status: 'draft' | 'provisioning' | 'active' | 'degraded' | 'maintenance' | 'retired';
  /** [PROTOCOL-CORE] Collection of core nodes in the network. */
  nodes?: any[];
  /** [PROTOCOL-CORE] Trace reference associated with this network. */
  trace?: any;
  /** [PROTOCOL-CORE] List of key events related to this network. */
  events?: any[];
}
