/**
 * © 2025 邦士（北京）网络科技有限公司
 * Licensed under the Apache License, Version 2.0.
 *
 * This file is part of the MPLP reference implementation.
 * It is NOT part of the frozen protocol specification.
 */
/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Common type definitions used across MPLP modules to ensure consistency and reduce duplication.
 */
export interface MplpCommonTypes {
}

export type MplpId = any;

export type Ref = object;

export type BaseMeta = any;
