/**
 * Copyright 2025 邦士（北京）网络科技有限公司.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Base model for all event structures in MPLP. Designed based on CloudEvents v1.0 core fields, providing unified event identification, type, source, and timestamp. ExecutionEvent, StateTransitionEvent, etc., are extensions of this.
 */
export interface MplpEvents {
  /** Unique identifier for the event (UUID v4). */
  event_id: any;
  /** Event type identifier, e.g., execution.started / vsl.transition.applied / plan.created. Uses dot-separated namespace format. */
  event_type: string;
  /** Event source, typically a module or component identifier. Can be a module name (e.g., 'context') or component path (e.g., 'runtime.ael'). */
  source: string;
  /** Event occurrence time (ISO 8601 format). */
  timestamp: string;
  /** Optional trace ID to associate the event with a specific Trace. */
  trace_id?: any;
  data?: any;
}
