/**
 * © 2025 邦士（北京）网络科技有限公司
 * Licensed under the Apache License, Version 2.0.
 *
 * This file is part of the MPLP reference implementation.
 * It is NOT part of the frozen protocol specification.
 */
/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Common metadata structure for all MPLP objects. Provides version control, creation info, tags, and cross-cutting concern declarations. All top-level objects in L2/L3/L4 should include the meta field.
 */
export interface MplpMetadata {
  /** MPLP protocol version, using Semantic Versioning. */
  protocol_version: string;
  /** Schema version used by the current object, using Semantic Versioning. */
  schema_version: string;
  /** Object creation time (ISO 8601 format). */
  created_at?: string;
  /** Creator identifier (User ID / Agent Name / System ID). */
  created_by?: string;
  /** Object last update time (ISO 8601 format). */
  updated_at?: string;
  /** Last updater identifier. */
  updated_by?: string;
  /** Set of tags for indexing/search. Supports custom classification and retrieval. */
  tags?: string[];
  /** Declares cross-cutting concerns enabled for the current object (one of the 9 concerns in Governance Plane). */
  cross_cutting?: 'coordination' | 'error-handling' | 'event-bus' | 'orchestration' | 'performance' | 'protocol-version' | 'security' | 'state-sync' | 'transaction'[];
}
