/**
 * © 2025 邦士（北京）网络科技有限公司
 * Licensed under the Apache License, Version 2.0.
 *
 * This file is part of the MPLP reference implementation.
 * It is NOT part of the frozen protocol specification.
 */
/* eslint-disable */
// Generated by simple-codegen.ts

/**
 * Common base fields for Trace / Span structures. Designed based on W3C Trace Context standard, providing a unified tracing context for the MPLP execution chain. Supports distributed tracing and parent-child relationships of execution steps.
 */
export interface MplpTraceBase {
  /** Identifier for a complete execution chain. All related Spans share the same trace_id. */
  trace_id: any;
  /** Identifier for the current step or operation. Each Span has a unique span_id. */
  span_id: any;
  /** Identifier of the parent step's span_id. Can be omitted if it is a root span. */
  parent_span_id?: any;
  /** Identifier of the Context Root. Associates the Trace with a specific project context. */
  context_id?: any;
  /** Additional attributes (key-value pairs) to extend trace information. Can contain custom metadata, tags, etc. */
  attributes?: { [key: string]: any };
}
