import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar configuration using autogenerated content to respect all _category_.json files
const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Intro page
    'intro',

    // Autogenerate all categories from docs folder
    // This respects each folder's _category_.json link configuration
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
