import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar configuration matching Antigravity's hierarchical structure
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'generated-index' },
      collapsed: false,
      items: [
        'intro',
        { type: 'autogenerated', dirName: '08-guides' }
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'generated-index' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '01-architecture' }],
    },
    {
      type: 'category',
      label: 'Modules',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '02-modules' }],
    },
    {
      type: 'category',
      label: 'Profiles',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '03-profiles' }],
    },
    {
      type: 'category',
      label: 'Observability',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '04-observability' }],
    },
    {
      type: 'category',
      label: 'Learning',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '05-learning' }],
    },
    {
      type: 'category',
      label: 'Runtime',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '06-runtime' }],
    },
    {
      type: 'category',
      label: 'Integration',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '07-integration' }],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },
    {
      type: 'category',
      label: 'Tests',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '09-tests' }],
    },
    {
      type: 'category',
      label: 'SDK',
      link: { type: 'generated-index' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '10-sdk' }],
    },
    {
      type: 'category',
      label: 'Examples',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '11-examples' }],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },
    {
      type: 'category',
      label: 'Governance',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '12-governance' }],
    },
    {
      type: 'category',
      label: 'Release',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '13-release' }],
    },
    {
      type: 'category',
      label: 'Ops',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '14-ops' }],
    },
    {
      type: 'category',
      label: 'Meta',
      link: { type: 'generated-index' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '99-meta' }],
    },
  ],
};

export default sidebars;
