import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar configuration aligned with T0-T4 Semantic Governance
const sidebars: SidebarsConfig = {
  docsSidebar: [
    // --------------------------------------------------------
    // T0: PROTOCOL FOUNDATION (Identity & Governance)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Protocol Foundation',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        'intro', // Getting Started / Intro
        {
          type: 'category',
          label: 'Governance',
          link: { type: 'generated-index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: '12-governance' }],
        },
        {
          type: 'category',
          label: 'Standards',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '15-standards' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // T1: SPECIFICATION (Normative)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Specification',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Architecture',
          link: { type: 'generated-index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: '01-architecture' }],
        },
        {
          type: 'category',
          label: 'Modules',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '02-modules' }],
        },
        {
          type: 'category',
          label: 'Profiles',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '03-profiles' }],
        },
        {
          type: 'category',
          label: 'Observability',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '04-observability' }],
        },
        {
          type: 'category',
          label: 'Runtime',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '14-runtime' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // T1/T2: VERIFICATION (Conformance)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Verification',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Golden Flows',
          link: { type: 'generated-index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: '06-golden-flows' }],
        },
        {
          type: 'category',
          label: 'Tests',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '09-tests' }],
        },
        {
          type: 'category',
          label: 'Compliance',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '16-compliance' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // T2/T3: IMPLEMENTATION (Builder Lens)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Implementation',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'SDK',
          link: { type: 'generated-index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: '10-sdk' }],
        },
        {
          type: 'category',
          label: 'Guides',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '08-guides' }],
        },
        {
          type: 'category',
          label: 'Examples',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '11-examples' }],
        },
        {
          type: 'category',
          label: 'Integration',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '07-integration' }],
        },
        {
          type: 'category',
          label: 'Learning',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '05-learning' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // T3/T4: ADOPTION (Ecosystem)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Adoption',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Enterprise',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '17-enterprise' }],
        },
        {
          type: 'category',
          label: 'Adoption',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '18-adoption' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // META (Operations)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Meta',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Release',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '13-release' }],
        },
        {
          type: 'category',
          label: 'Meta',
          link: { type: 'generated-index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: '99-meta' }],
        },
      ]
    },
  ],
};

export default sidebars;
