# Copyright 2025 邦士（北京）网络科技有限公司.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by generate-py-models-from-schemas.ts
from __future__ import annotations
from typing import Any, Dict, List, Optional, Literal
from pydantic import BaseModel, Field, ConfigDict

class ContextCoreProperties(BaseModel):
    """ContextCoreProperties"""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol and schema metadata (version, source, cross-cutting tags, etc.).")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Context.")
    root: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] Context root node definition (business domain, environment, entry point resources, etc.).")
    title: str = Field(..., description="[PROTOCOL-CORE] Context title, used for human and Agent identification of the project/session.")
    summary: Optional[str] = Field(None, description="[PROTOCOL-CORE] Brief summary of the Context (background, scope, etc.).")
    status: Literal["draft", "active", "suspended", "archived", "closed"] = Field(..., description="[PROTOCOL-CORE] Current lifecycle status of the Context.")
    tags: Optional[List[str]] = Field(None, description="[PROTOCOL-CORE] List of tags for classification and retrieval.")
    language: Optional[str] = Field(None, description="[PROTOCOL-CORE] Primary working language of the Context (e.g., en, zh-CN).")
    owner_role: Optional[str] = Field(None, description="[PROTOCOL-CORE] Identifier of the primary owner role (should correspond to role_id in Role module).")
    constraints: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Key constraints for the Context, such as security boundaries, compliance requirements, budget, or deadlines.")
    created_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Context creation time (ISO 8601).")
    updated_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Context last update time (ISO 8601).")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Main Trace reference bound to this Context (for global tracing).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly related to this Context (creation, status change, archiving, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class Uuid(BaseModel):
    """[DEPRECATED] Please use common/identifiers.schema.json. This definition is retained for backward compatibility only and is no longer recommended for reference."""
    pass
    model_config = ConfigDict(validate_assignment=True)

class Context(BaseModel):
    """Context Module Core Protocol: Describes the context resources and their minimal required semantics (Core Profile) for a multi-agent collaboration project/session."""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol and schema metadata (version, source, cross-cutting tags, etc.).")
    governance: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status.")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Context.")
    root: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] Context root node definition (business domain, environment, entry point resources, etc.).")
    title: str = Field(..., description="[PROTOCOL-CORE] Context title, used for human and Agent identification of the project/session.")
    summary: Optional[str] = Field(None, description="[PROTOCOL-CORE] Brief summary of the Context (background, scope, etc.).")
    status: Literal["draft", "active", "suspended", "archived", "closed"] = Field(..., description="[PROTOCOL-CORE] Current lifecycle status of the Context.")
    tags: Optional[List[str]] = Field(None, description="[PROTOCOL-CORE] List of tags for classification and retrieval.")
    language: Optional[str] = Field(None, description="[PROTOCOL-CORE] Primary working language of the Context (e.g., en, zh-CN).")
    owner_role: Optional[str] = Field(None, description="[PROTOCOL-CORE] Identifier of the primary owner role (should correspond to role_id in Role module).")
    constraints: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Key constraints for the Context, such as security boundaries, compliance requirements, budget, or deadlines.")
    created_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Context creation time (ISO 8601).")
    updated_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Context last update time (ISO 8601).")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Main Trace reference bound to this Context (for global tracing).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly related to this Context (creation, status change, archiving, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class PlanCoreProperties(BaseModel):
    """PlanCoreProperties"""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol schema metadata (version, source, cross-cutting tags, etc.).")
    plan_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Plan.")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Identifier of the Context this Plan belongs to.")
    title: str = Field(..., description="[PROTOCOL-CORE] Plan title (brief description for humans and Agents).")
    objective: str = Field(..., description="[PROTOCOL-CORE] Description of the objective to be achieved by the Plan.")
    status: Literal["draft", "proposed", "approved", "in_progress", "completed", "cancelled", "failed"] = Field(..., description="[PROTOCOL-CORE] Status of the Plan in its lifecycle.")
    steps: List[PlanStepCore] = Field(..., description="[PROTOCOL-CORE] List of core steps decomposed from the Plan.")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Main execution trace reference associated with this Plan.")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly associated with this Plan (changes, approvals, status transitions, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class PlanStepCore(BaseModel):
    """[PROTOCOL-CORE] Minimal required semantics for a plan step (excluding execution engine, scheduling policy implementation details)."""
    step_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the step.")
    description: str = Field(..., description="[PROTOCOL-CORE] Content of the work to be completed in the step.")
    status: Literal["pending", "in_progress", "completed", "blocked", "skipped", "failed"] = Field(..., description="[PROTOCOL-CORE] Current status of the step.")
    dependencies: Optional[List[str]] = Field(None, description="[PROTOCOL-CORE] List of other step IDs that this step depends on.")
    agent_role: Optional[str] = Field(None, description="[PROTOCOL-CORE] Identifier of the role responsible for this step (should correspond to role_id in Role module).")
    order_index: Optional[int] = Field(None, description="[PROTOCOL-CORE] Sort index in the current Plan, used for defining execution order or display order.")
    model_config = ConfigDict(validate_assignment=True)

class Plan(BaseModel):
    """Plan Module Core Protocol: Describes the plan objects and their lifecycle minimal required semantics (Core Profile) in multi-agent collaboration."""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol schema metadata (version, source, cross-cutting tags, etc.).")
    plan_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Plan.")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Identifier of the Context this Plan belongs to.")
    title: str = Field(..., description="[PROTOCOL-CORE] Plan title (brief description for humans and Agents).")
    objective: str = Field(..., description="[PROTOCOL-CORE] Description of the objective to be achieved by the Plan.")
    status: Literal["draft", "proposed", "approved", "in_progress", "completed", "cancelled", "failed"] = Field(..., description="[PROTOCOL-CORE] Status of the Plan in its lifecycle.")
    steps: List[PlanStepCore] = Field(..., description="[PROTOCOL-CORE] List of core steps decomposed from the Plan.")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Main execution trace reference associated with this Plan.")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly associated with this Plan (changes, approvals, status transitions, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class ConfirmCoreProperties(BaseModel):
    """ConfirmCoreProperties"""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol schema metadata (version, source, cross-cutting tags, etc.).")
    confirm_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the approval request.")
    target_type: Literal["context", "plan", "trace", "extension", "other"] = Field(..., description="[PROTOCOL-CORE] Approval target type (type of the resource being approved).")
    target_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier of the resource being approved.")
    status: Literal["pending", "approved", "rejected", "cancelled"] = Field(..., description="[PROTOCOL-CORE] Current status of the approval request.")
    requested_by_role: str = Field(..., description="[PROTOCOL-CORE] Identifier of the role initiating the approval request (should correspond to role_id in Role module).")
    requested_at: str = Field(..., description="[PROTOCOL-CORE] Approval request creation time (ISO 8601).")
    reason: Optional[str] = Field(None, description="[PROTOCOL-CORE] Reason for the request, for humans and Agents.")
    decisions: Optional[List[ConfirmDecisionCore]] = Field(None, description="[PROTOCOL-CORE] List of decision records related to this Confirm request.")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Trace reference bound to this Confirm request (for cross-module tracing).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly related to this Confirm request (creation, decision, cancellation, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class ConfirmDecisionCore(BaseModel):
    """[PROTOCOL-CORE] Minimal required semantics for a single approval decision record."""
    decision_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the decision record.")
    status: Literal["approved", "rejected", "cancelled"] = Field(..., description="[PROTOCOL-CORE] Decision result status.")
    decided_by_role: str = Field(..., description="[PROTOCOL-CORE] Identifier of the role making the decision (should correspond to role_id in Role module).")
    decided_at: str = Field(..., description="[PROTOCOL-CORE] Decision time (ISO 8601).")
    reason: Optional[str] = Field(None, description="[PROTOCOL-CORE] Summary of the decision reason (optional).")
    model_config = ConfigDict(validate_assignment=True)

class Confirm(BaseModel):
    """Confirm Module Core Protocol: Describes the minimal required semantics (Core Profile) for approval requests and decision records."""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol schema metadata (version, source, cross-cutting tags, etc.).")
    governance: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status.")
    confirm_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the approval request.")
    target_type: Literal["context", "plan", "trace", "extension", "other"] = Field(..., description="[PROTOCOL-CORE] Approval target type (type of the resource being approved).")
    target_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier of the resource being approved.")
    status: Literal["pending", "approved", "rejected", "cancelled"] = Field(..., description="[PROTOCOL-CORE] Current status of the approval request.")
    requested_by_role: str = Field(..., description="[PROTOCOL-CORE] Identifier of the role initiating the approval request (should correspond to role_id in Role module).")
    requested_at: str = Field(..., description="[PROTOCOL-CORE] Approval request creation time (ISO 8601).")
    reason: Optional[str] = Field(None, description="[PROTOCOL-CORE] Reason for the request, for humans and Agents.")
    decisions: Optional[List[ConfirmDecisionCore]] = Field(None, description="[PROTOCOL-CORE] List of decision records related to this Confirm request.")
    trace: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Trace reference bound to this Confirm request (for cross-module tracing).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of key events directly related to this Confirm request (creation, decision, cancellation, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class TraceCoreProperties(BaseModel):
    """TraceCoreProperties"""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol and schema metadata.")
    trace_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Trace.")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Identifier of the Context this Trace belongs to.")
    plan_id: Optional[str] = Field(None, description="[PROTOCOL-CORE] Identifier of the Plan associated with this Trace (if any).")
    root_span: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] Root span definition of the Trace (follows L1 trace-base structure).")
    status: Literal["pending", "running", "completed", "failed", "cancelled"] = Field(..., description="[PROTOCOL-CORE] Current status of the Trace.")
    started_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Trace start time (ISO 8601).")
    finished_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Trace finish time (ISO 8601, optional if not finished).")
    segments: Optional[List[TraceSegmentCore]] = Field(None, description="[PROTOCOL-CORE] Key execution segments in the Trace (can correspond to multiple spans or phased aggregations).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of events directly related to this Trace (errors, retries, status changes, etc.).")
    model_config = ConfigDict(validate_assignment=True)

class TraceSegmentCore(BaseModel):
    """[PROTOCOL-CORE] Key segments in execution tracing, used to express an auditable execution interval at the protocol layer."""
    segment_id: str = Field(..., description="[PROTOCOL-CORE] Segment identifier.")
    parent_segment_id: Optional[str] = Field(None, description="[PROTOCOL-CORE] Parent segment identifier (optional if root segment).")
    label: str = Field(..., description="[PROTOCOL-CORE] Segment label/name, for human and Agent identification of the interval.")
    status: Literal["pending", "running", "completed", "failed", "cancelled", "skipped"] = Field(..., description="[PROTOCOL-CORE] Segment status.")
    started_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Segment start time.")
    finished_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Segment finish time (optional if not finished).")
    attributes: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Key context attributes related to this segment (key-value form, for tracing and audit).")
    model_config = ConfigDict(validate_assignment=True)

class Trace(BaseModel):
    """Trace Module Core Protocol: Describes the minimal required semantics (Core Profile) for execution trace resources (Trace) and their key segments and events."""
    meta: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] MPLP protocol and schema metadata.")
    governance: Optional[Dict[str, Any]] = Field(None, description="[PROTOCOL-CORE] Governance metadata for lifecycle management, truth domain authority, and locking status.")
    trace_id: str = Field(..., description="[PROTOCOL-CORE] Global unique identifier for the Trace.")
    context_id: str = Field(..., description="[PROTOCOL-CORE] Identifier of the Context this Trace belongs to.")
    plan_id: Optional[str] = Field(None, description="[PROTOCOL-CORE] Identifier of the Plan associated with this Trace (if any).")
    root_span: Dict[str, Any] = Field(..., description="[PROTOCOL-CORE] Root span definition of the Trace (follows L1 trace-base structure).")
    status: Literal["pending", "running", "completed", "failed", "cancelled"] = Field(..., description="[PROTOCOL-CORE] Current status of the Trace.")
    started_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Trace start time (ISO 8601).")
    finished_at: Optional[str] = Field(None, description="[PROTOCOL-CORE] Trace finish time (ISO 8601, optional if not finished).")
    segments: Optional[List[TraceSegmentCore]] = Field(None, description="[PROTOCOL-CORE] Key execution segments in the Trace (can correspond to multiple spans or phased aggregations).")
    events: Optional[List[Dict[str, Any]]] = Field(None, description="[PROTOCOL-CORE] List of events directly related to this Trace (errors, retries, status changes, etc.).")
    model_config = ConfigDict(validate_assignment=True)

