name: Commit Message Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  validate-commits:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate commit messages
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, validate all commits in the PR
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            # For pushes, validate the last commit
            npx commitlint --from HEAD~1 --to HEAD --verbose
          fi
          
      - name: Comment on PR (if validation fails)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            const comment = `## ❌ Commit Message Validation Failed
            
            Your commit messages don't follow the [Conventional Commits](https://www.conventionalcommits.org/) specification.
            
            ### Expected Format:
            \`\`\`
            <type>[optional scope]: <description>
            
            [optional body]
            
            [optional footer(s)]
            \`\`\`
            
            ### Examples:
            - \`feat(schema): add new validation rules\`
            - \`fix(api): resolve authentication issue\`
            - \`docs(readme): update installation guide\`
            - \`test(unit): add tests for core functions\`
            
            ### Valid Types:
            - **feat**: New feature
            - **fix**: Bug fix
            - **docs**: Documentation changes
            - **style**: Code style changes
            - **refactor**: Code refactoring
            - **perf**: Performance improvements
            - **test**: Adding or updating tests
            - **build**: Build system changes
            - **ci**: CI/CD changes
            - **chore**: Other changes
            
            Please update your commit messages and force-push to this branch.`;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });
            
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            schema
            example
            release
          scopes: |
            schema
            core
            api
            protocol
            docs
            readme
            changelog
            ci
            build
            deps
            config
            test
            e2e
            unit
            integration
            examples
            demo
            scripts
            tools
            lint
            release
            version
            security
            audit
            perf
            optimization
            i18n
            l10n
            ui
            ux
            style
          requireScope: false
          disallowScopes: |
            release
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          wip: true
          validateSingleCommit: false