name: Validate JSON Examples

on:
  push:
    paths:
      - "examples/**"
      - "schemas/**"
      - ".github/workflows/validate-examples.yml"
  pull_request:
    paths:
      - "examples/**"
      - "schemas/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Validate All Examples Against Schemas
        run: node scripts/validate-examples.js